### ISSUE TITLE
Please allow to select my own actor and color on wws-message-post

### ISSUE THREAD

**Issue by bgewehr** [stefanopog/node-red-contrib-wws#1]
Currently, all posts are hard-coded "RED" and the actor is hard-coded to the config.author. Please allow me to tell my preferred color in the msg object and change the actor as well:

Example from a connections->WWS use case:
```
msg.actor.name = msg.payload.actor.displayName;
msg.actor.url = "";
msg.actor.avatar = "";

msg.color =   "#FF8000";
```

Result is:

![image](https://user-images.githubusercontent.com/4056277/35378699-ffe6c122-01b3-11e8-8793-c4bc84d3bf28.png)

Please let me control the color and the actor.

**Comment by arsu77** [comment]
Please check latest version 1.0.3 which is a complete rework of the nodes.
This feature is now available.
