### ISSUE TITLE
Support for graphQL Beta Features

### ISSUE THREAD

**Issue by arsu77** [stefanopog/node-red-contrib-wws#2]
In order to use the BETA features within graphQL queries or mutations it is good to have the possibility to activate by check box the different features.

[PUBLIC enabled GraphQL Tool](https://developer.watsonwork.ibm.com/tools/graphql)
[BETA enabled GraphQL Tool](https://developer.watsonwork.ibm.com/tools/graphql?apiType=beta,public)

**Comment by arsu77** [comment]
Master contains already a version which allows to set the view type property.
<img width="499" alt="screen1" src="https://user-images.githubusercontent.com/26877932/40658343-461b5150-634b-11e8-8a66-d3a7d2b40e85.png">

**Comment by stefanopog** [comment]
As discussed, I would privilege the use of CHECKBOXES for BETA and EXPERIMENTAL. 
They are more immediate to understand for the developer and to use also

**Comment by arsu77** [comment]
Stefano already incorporated the changes hence closing the issue
